### ISSUE TITLE
PublishHtmlReport@1 Fails to Display Multiple HTML Report Tabs on Windows Agents

### ISSUE THREAD

**Issue by dzhukovsky** [blakyaks/azure-pipeline-html-reports#20]
I am experiencing an issue with the `PublishHtmlReport@1` task in Azure DevOps. When running this task on Windows agents, the expected HTML report tabs do not appear in the pipeline results. However, the same configuration works correctly on Ubuntu agents, displaying the HTML report tabs as intended.

**Steps to Reproduce:**
1. Configure an Azure DevOps pipeline with the following YAML snippet:
```yml
pool:
  vmImage: windows-latest

steps:
  - task: PublishHtmlReport@1
    inputs:
      reportDir: '$(System.DefaultWorkingDirectory)'
```

2. Ensure that the specified `reportDir` contains the `test1.html` and `test2.html` files and related content.
3. Run the pipeline on a Windows agent.

**Expected Outcome:**
The pipeline should display an HTML report tabs with the contents of the `test1.html` and `test2.html` files.

**Actual Outcome:**
The HTML report tab is not displayed in the pipeline results when executed on Windows agents.
